name: Publish

on:
  push:
    branches:
    - sources

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Prepare handout
      run: |
        cp ./slides.tex ./handout.tex
        sed -i "1s/.*/\\\\documentclass\[handout\]\{beamer\}/" ./handout.tex
    - name: Compile LaTeX sources
      uses: xu-cheng/latex-action@2.4.0
      with:
        pre_compile: tlmgr update --self && tlmgr update --all
        root_file: |
          handout.tex
          paper.tex
          slides.tex
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.8.0
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_branch: master
        publish_dir: ./
        allow_empty_commit: true
        force_orphan: true
